// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhvmpowewkeqvitshhna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5odm1wb3dld2tlcXZpdHNoaG5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0MTA1ODAsImV4cCI6MjA3OTk4NjU4MH0.W4AY0gO08cNMt4jKvWnuYQzoI4tW2jd0A5rze4W-yrw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});